name: twitter_oauth
description: Twitter oath.
version: 0.0.1
homepage: "https://yegobox.com"
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  convert: ^3.0.1
  crypto: ^3.0.1
  isar: ^2.1.4
  isar_flutter_libs: ^2.1.4 # contains the binaries
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.0.18
  path_provider: ^2.0.8
  get_storage: ^2.0.3
  oauth1: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  isar_generator: ^2.1.4
  build_runner: any

flutter:
